/* Created : Tue Jun 11 15:18:22 CDT 2019
   User    : aes
   Project : cert_cfs
   Script  : /virtualpcs/repos/um/fcc/fcc_fsw/ccdd/scripts/CCSDS_V2_Mids.js
   Group(s): cfs_mids
*/

#ifndef _auto_cfs_mids_h_
#define _auto_cfs_mids_h_

/* SubSystem Macros */
#define GRP1_CFS_ID                                    0x07
#define GRP2_CFS_ID                                    0x08
#define GRP3_CFS_ID                                    0x09
#define GRP4_CFS_ID                                    0x0a

/* Command message IDs */
#define GRP1_CFS_MIN_CMD_MID                           0x9E01
#define GRP1_CFS_CI_CMD_MID                            0x9E01
#define GRP1_CFS_CI_SEND_HK_MID                        0x9E02
#define GRP1_CFS_CI_WAKEUP_MID                         0x9E03
#define GRP1_CFS_CI_GATE_CMD_MID                       0x9E04
#define GRP1_CFS_SBN_CMD_MID                           0x9E05
#define GRP1_CFS_SBN_SEND_HK_MID                       0x9E06
#define GRP1_CFS_SBN_WAKEUP_MID                        0x9E07
#define GRP1_CFS_SCH_CMD_MID                           0x9E08
#define GRP1_CFS_SCH_SEND_HK_MID                       0x9E09
#define GRP1_CFS_SCH_TT_CMD_MID                        0x9E0A
#define GRP1_CFS_SCH_TT_SEND_HK_MID                    0x9E0B
#define GRP1_CFS_TO_CMD_MID                            0x9E0C
#define GRP1_CFS_TO_SEND_HK_MID                        0x9E0D
#define GRP1_CFS_TO_WAKEUP_MID                         0x9E0E
#define GRP1_CFS_TTE_MGR_CMD_MID                       0x9E0F
#define GRP1_CFS_TTE_MGR_SEND_HK_MID                   0x9E10
#define GRP1_CFS_AUDIO_CMD_MID                         0x9E11
#define GRP1_CFS_AUDIO_SEND_HK_MID                     0x9E12
#define GRP1_CFS_AUDIO_WAKEUP_MID                      0x9E13
#define GRP1_CFS_AUDIO_SIM_UDP_SND_MID                 0x9E14
#define GRP1_CFS_AUDIO_SIM_UDP_RCV_MID                 0x9E15
#define GRP1_CFS_MSM_CMD_MID                           0x9E16
#define GRP1_CFS_MSM_SEND_HK_MID                       0x9E17
#define GRP1_CFS_MSM_WAKEUP_MID                        0x9E18
#define GRP1_CFS_VIDEO_CMD_MID                         0x9E19
#define GRP1_CFS_VIDEO_SEND_HK_MID                     0x9E1A
#define GRP1_CFS_VIDEO_WAKEUP_MID                      0x9E1B
#define GRP1_CFS_CT_CMD_MID                            0x9E1C
#define GRP1_CFS_CT_SEND_HK_MID                        0x9E1D
#define GRP1_CFS_CT_WAKEUP_MID                         0x9E1E
#define GRP1_CFS_ECLS_CMD_MID                          0x9E1F
#define GRP1_CFS_ECLS_SEND_HK_MID                      0x9E20
#define GRP1_CFS_ECLS_WAKEUP_MID                       0x9E21
#define GRP1_CFS_LIGHTING_CMD_MID                      0x9E22
#define GRP1_CFS_LIGHTING_SEND_HK_MID                  0x9E23
#define GRP1_CFS_LIGHTING_WAKEUP_MID                   0x9E24
#define GRP1_CFS_POWER_CMD_MID                         0x9E25
#define GRP1_CFS_POWER_SEND_HK_MID                     0x9E26
#define GRP1_CFS_POWER_WAKEUP_MID                      0x9E27
#define GRP1_CFS_UM_CMD_ECLSS_PCA_MID                  0x9E28
#define GRP1_CFS_UM_CMD_ECLSS_VPA_MID                  0x9E29
#define GRP1_CFS_UM_CMD_ECLSS_CAL_MID                  0x9E2A
#define GRP1_CFS_UM_CMD_SBN_ECLSS_PCA_MID              0x9E2B
#define GRP1_CFS_UM_CMD_SBN_ECLSS_VPA_MID              0x9E2C
#define GRP1_CFS_UM_CMD_SBN_ECLSS_CAL_MID              0x9E2D
#define GRP1_CFS_MAX_CMD_MID                           0x9E2D

#define GRP2_CFS_MIN_CMD_MID                           0x9001
#define GRP2_CFS_CI_CMD_MID                            0x9001
#define GRP2_CFS_CI_SEND_HK_MID                        0x9002
#define GRP2_CFS_CI_WAKEUP_MID                         0x9003
#define GRP2_CFS_CI_GATE_CMD_MID                       0x9004
#define GRP2_CFS_SBN_CMD_MID                           0x9005
#define GRP2_CFS_SBN_SEND_HK_MID                       0x9006
#define GRP2_CFS_SBN_WAKEUP_MID                        0x9007
#define GRP2_CFS_SCH_CMD_MID                           0x9008
#define GRP2_CFS_SCH_SEND_HK_MID                       0x9009
#define GRP2_CFS_SCH_TT_CMD_MID                        0x900A
#define GRP2_CFS_SCH_TT_SEND_HK_MID                    0x900B
#define GRP2_CFS_TO_CMD_MID                            0x900C
#define GRP2_CFS_TO_SEND_HK_MID                        0x900D
#define GRP2_CFS_TO_WAKEUP_MID                         0x900E
#define GRP2_CFS_TTE_MGR_CMD_MID                       0x900F
#define GRP2_CFS_TTE_MGR_SEND_HK_MID                   0x9010
#define GRP2_CFS_AUDIO_CMD_MID                         0x9011
#define GRP2_CFS_AUDIO_SEND_HK_MID                     0x9012
#define GRP2_CFS_AUDIO_WAKEUP_MID                      0x9013
#define GRP2_CFS_AUDIO_SIM_UDP_SND_MID                 0x9014
#define GRP2_CFS_AUDIO_SIM_UDP_RCV_MID                 0x9015
#define GRP2_CFS_MSM_CMD_MID                           0x9016
#define GRP2_CFS_MSM_SEND_HK_MID                       0x9017
#define GRP2_CFS_MSM_WAKEUP_MID                        0x9018
#define GRP2_CFS_VIDEO_CMD_MID                         0x9019
#define GRP2_CFS_VIDEO_SEND_HK_MID                     0x901A
#define GRP2_CFS_VIDEO_WAKEUP_MID                      0x901B
#define GRP2_CFS_CT_CMD_MID                            0x901C
#define GRP2_CFS_CT_SEND_HK_MID                        0x901D
#define GRP2_CFS_CT_WAKEUP_MID                         0x901E
#define GRP2_CFS_ECLS_CMD_MID                          0x901F
#define GRP2_CFS_ECLS_SEND_HK_MID                      0x9020
#define GRP2_CFS_ECLS_WAKEUP_MID                       0x9021
#define GRP2_CFS_LIGHTING_CMD_MID                      0x9022
#define GRP2_CFS_LIGHTING_SEND_HK_MID                  0x9023
#define GRP2_CFS_LIGHTING_WAKEUP_MID                   0x9024
#define GRP2_CFS_POWER_CMD_MID                         0x9025
#define GRP2_CFS_POWER_SEND_HK_MID                     0x9026
#define GRP2_CFS_POWER_WAKEUP_MID                      0x9027
#define GRP2_CFS_UM_CMD_ECLSS_PCA_MID                  0x9028
#define GRP2_CFS_UM_CMD_ECLSS_VPA_MID                  0x9029
#define GRP2_CFS_UM_CMD_ECLSS_CAL_MID                  0x902A
#define GRP2_CFS_UM_CMD_SBN_ECLSS_PCA_MID              0x902B
#define GRP2_CFS_UM_CMD_SBN_ECLSS_VPA_MID              0x902C
#define GRP2_CFS_UM_CMD_SBN_ECLSS_CAL_MID              0x902D
#define GRP2_CFS_MAX_CMD_MID                           0x902D

#define GRP3_CFS_MIN_CMD_MID                           0x9201
#define GRP3_CFS_CI_CMD_MID                            0x9201
#define GRP3_CFS_CI_SEND_HK_MID                        0x9202
#define GRP3_CFS_CI_WAKEUP_MID                         0x9203
#define GRP3_CFS_CI_GATE_CMD_MID                       0x9204
#define GRP3_CFS_SBN_CMD_MID                           0x9205
#define GRP3_CFS_SBN_SEND_HK_MID                       0x9206
#define GRP3_CFS_SBN_WAKEUP_MID                        0x9207
#define GRP3_CFS_SCH_CMD_MID                           0x9208
#define GRP3_CFS_SCH_SEND_HK_MID                       0x9209
#define GRP3_CFS_SCH_TT_CMD_MID                        0x920A
#define GRP3_CFS_SCH_TT_SEND_HK_MID                    0x920B
#define GRP3_CFS_TO_CMD_MID                            0x920C
#define GRP3_CFS_TO_SEND_HK_MID                        0x920D
#define GRP3_CFS_TO_WAKEUP_MID                         0x920E
#define GRP3_CFS_TTE_MGR_CMD_MID                       0x920F
#define GRP3_CFS_TTE_MGR_SEND_HK_MID                   0x9210
#define GRP3_CFS_AUDIO_CMD_MID                         0x9211
#define GRP3_CFS_AUDIO_SEND_HK_MID                     0x9212
#define GRP3_CFS_AUDIO_WAKEUP_MID                      0x9213
#define GRP3_CFS_AUDIO_SIM_UDP_SND_MID                 0x9214
#define GRP3_CFS_AUDIO_SIM_UDP_RCV_MID                 0x9215
#define GRP3_CFS_MSM_CMD_MID                           0x9216
#define GRP3_CFS_MSM_SEND_HK_MID                       0x9217
#define GRP3_CFS_MSM_WAKEUP_MID                        0x9218
#define GRP3_CFS_VIDEO_CMD_MID                         0x9219
#define GRP3_CFS_VIDEO_SEND_HK_MID                     0x921A
#define GRP3_CFS_VIDEO_WAKEUP_MID                      0x921B
#define GRP3_CFS_CT_CMD_MID                            0x921C
#define GRP3_CFS_CT_SEND_HK_MID                        0x921D
#define GRP3_CFS_CT_WAKEUP_MID                         0x921E
#define GRP3_CFS_ECLS_CMD_MID                          0x921F
#define GRP3_CFS_ECLS_SEND_HK_MID                      0x9220
#define GRP3_CFS_ECLS_WAKEUP_MID                       0x9221
#define GRP3_CFS_LIGHTING_CMD_MID                      0x9222
#define GRP3_CFS_LIGHTING_SEND_HK_MID                  0x9223
#define GRP3_CFS_LIGHTING_WAKEUP_MID                   0x9224
#define GRP3_CFS_POWER_CMD_MID                         0x9225
#define GRP3_CFS_POWER_SEND_HK_MID                     0x9226
#define GRP3_CFS_POWER_WAKEUP_MID                      0x9227
#define GRP3_CFS_UM_CMD_ECLSS_PCA_MID                  0x9228
#define GRP3_CFS_UM_CMD_ECLSS_VPA_MID                  0x9229
#define GRP3_CFS_UM_CMD_ECLSS_CAL_MID                  0x922A
#define GRP3_CFS_UM_CMD_SBN_ECLSS_PCA_MID              0x922B
#define GRP3_CFS_UM_CMD_SBN_ECLSS_VPA_MID              0x922C
#define GRP3_CFS_UM_CMD_SBN_ECLSS_CAL_MID              0x922D
#define GRP3_CFS_MAX_CMD_MID                           0x922D

#define GRP4_CFS_MIN_CMD_MID                           0x9401
#define GRP4_CFS_CI_CMD_MID                            0x9401
#define GRP4_CFS_CI_SEND_HK_MID                        0x9402
#define GRP4_CFS_CI_WAKEUP_MID                         0x9403
#define GRP4_CFS_CI_GATE_CMD_MID                       0x9404
#define GRP4_CFS_SBN_CMD_MID                           0x9405
#define GRP4_CFS_SBN_SEND_HK_MID                       0x9406
#define GRP4_CFS_SBN_WAKEUP_MID                        0x9407
#define GRP4_CFS_SCH_CMD_MID                           0x9408
#define GRP4_CFS_SCH_SEND_HK_MID                       0x9409
#define GRP4_CFS_SCH_TT_CMD_MID                        0x940A
#define GRP4_CFS_SCH_TT_SEND_HK_MID                    0x940B
#define GRP4_CFS_TO_CMD_MID                            0x940C
#define GRP4_CFS_TO_SEND_HK_MID                        0x940D
#define GRP4_CFS_TO_WAKEUP_MID                         0x940E
#define GRP4_CFS_TTE_MGR_CMD_MID                       0x940F
#define GRP4_CFS_TTE_MGR_SEND_HK_MID                   0x9410
#define GRP4_CFS_AUDIO_CMD_MID                         0x9411
#define GRP4_CFS_AUDIO_SEND_HK_MID                     0x9412
#define GRP4_CFS_AUDIO_WAKEUP_MID                      0x9413
#define GRP4_CFS_AUDIO_SIM_UDP_SND_MID                 0x9414
#define GRP4_CFS_AUDIO_SIM_UDP_RCV_MID                 0x9415
#define GRP4_CFS_MSM_CMD_MID                           0x9416
#define GRP4_CFS_MSM_SEND_HK_MID                       0x9417
#define GRP4_CFS_MSM_WAKEUP_MID                        0x9418
#define GRP4_CFS_VIDEO_CMD_MID                         0x9419
#define GRP4_CFS_VIDEO_SEND_HK_MID                     0x941A
#define GRP4_CFS_VIDEO_WAKEUP_MID                      0x941B
#define GRP4_CFS_CT_CMD_MID                            0x941C
#define GRP4_CFS_CT_SEND_HK_MID                        0x941D
#define GRP4_CFS_CT_WAKEUP_MID                         0x941E
#define GRP4_CFS_ECLS_CMD_MID                          0x941F
#define GRP4_CFS_ECLS_SEND_HK_MID                      0x9420
#define GRP4_CFS_ECLS_WAKEUP_MID                       0x9421
#define GRP4_CFS_LIGHTING_CMD_MID                      0x9422
#define GRP4_CFS_LIGHTING_SEND_HK_MID                  0x9423
#define GRP4_CFS_LIGHTING_WAKEUP_MID                   0x9424
#define GRP4_CFS_POWER_CMD_MID                         0x9425
#define GRP4_CFS_POWER_SEND_HK_MID                     0x9426
#define GRP4_CFS_POWER_WAKEUP_MID                      0x9427
#define GRP4_CFS_UM_CMD_ECLSS_PCA_MID                  0x9428
#define GRP4_CFS_UM_CMD_ECLSS_VPA_MID                  0x9429
#define GRP4_CFS_UM_CMD_ECLSS_CAL_MID                  0x942A
#define GRP4_CFS_UM_CMD_SBN_ECLSS_PCA_MID              0x942B
#define GRP4_CFS_UM_CMD_SBN_ECLSS_VPA_MID              0x942C
#define GRP4_CFS_UM_CMD_SBN_ECLSS_CAL_MID              0x942D
#define GRP4_CFS_MAX_CMD_MID                           0x942D

/* Telemetry message IDs */
#define GRP1_CFS_MIN_TLM_MID                           0x0E01
#define GRP1_CFS_CI_HK_TLM_MID                         0x0E01
#define GRP1_CFS_CI_OUT_DATA_MID                       0x0E02
#define GRP1_CFS_SBN_TLM_MID                           0x0E03
#define GRP1_CFS_SCH_HK_TLM_MID                        0x0E04
#define GRP1_CFS_SCH_DIAG_TLM_MID                      0x0E05
#define GRP1_CFS_SCH_TT_HK_TLM_MID                     0x0E06
#define GRP1_CFS_TO_HK_TLM_MID                         0x0E07
#define GRP1_CFS_TO_OUT_DATA_MID                       0x0E08
#define GRP1_CFS_TO_DATA_TYPE_MID                      0x0E09
#define GRP1_CFS_TTE_MGR_HK_TLM_MID                    0x0E0A
#define GRP1_CFS_AUDIO_HK_TLM_MID                      0x0E0B
#define GRP1_CFS_AUDIO_OUT_DATA_MID                    0x0E0C
#define GRP1_CFS_MSM_HK_TLM_MID                        0x0E0D
#define GRP1_CFS_MSM_OUT_DATA_MID                      0x0E0E
#define GRP1_CFS_VIDEO_HK_TLM_MID                      0x0E0F
#define GRP1_CFS_VIDEO_OUT_DATA_MID                    0x0E10
#define GRP1_CFS_CT_HK_TLM_MID                         0x0E11
#define GRP1_CFS_CT_OUT_DATA_MID                       0x0E12
#define GRP1_CFS_ECLS_HK_TLM_MID                       0x0E13
#define GRP1_CFS_ECLS_OUT_DATA_MID                     0x0E14
#define GRP1_CFS_LIGHTING_HK_TLM_MID                   0x0E15
#define GRP1_CFS_LIGHTING_OUT_DATA_MID                 0x0E16
#define GRP1_CFS_POWER_HK_TLM_MID                      0x0E17
#define GRP1_CFS_POWER_OUT_DATA_MID                    0x0E18
#define GRP1_CFS_UM_ECLSS_TLM_MID					   0x0E19
#define GRP1_CFS_MAX_TLM_MID                           0x0E19

#define GRP2_CFS_MIN_TLM_MID                           0x1001
#define GRP2_CFS_CI_HK_TLM_MID                         0x1001
#define GRP2_CFS_CI_OUT_DATA_MID                       0x1002
#define GRP2_CFS_SBN_TLM_MID                           0x1003
#define GRP2_CFS_SCH_HK_TLM_MID                        0x1004
#define GRP2_CFS_SCH_DIAG_TLM_MID                      0x1005
#define GRP2_CFS_SCH_TT_HK_TLM_MID                     0x1006
#define GRP2_CFS_TO_HK_TLM_MID                         0x1007
#define GRP2_CFS_TO_OUT_DATA_MID                       0x1008
#define GRP2_CFS_TO_DATA_TYPE_MID                      0x1009
#define GRP2_CFS_TTE_MGR_HK_TLM_MID                    0x100A
#define GRP2_CFS_AUDIO_HK_TLM_MID                      0x100B
#define GRP2_CFS_AUDIO_OUT_DATA_MID                    0x100C
#define GRP2_CFS_MSM_HK_TLM_MID                        0x100D
#define GRP2_CFS_MSM_OUT_DATA_MID                      0x100E
#define GRP2_CFS_VIDEO_HK_TLM_MID                      0x100F
#define GRP2_CFS_VIDEO_OUT_DATA_MID                    0x1010
#define GRP2_CFS_CT_HK_TLM_MID                         0x1011
#define GRP2_CFS_CT_OUT_DATA_MID                       0x1012
#define GRP2_CFS_ECLS_HK_TLM_MID                       0x1013
#define GRP2_CFS_ECLS_OUT_DATA_MID                     0x1014
#define GRP2_CFS_LIGHTING_HK_TLM_MID                   0x1015
#define GRP2_CFS_LIGHTING_OUT_DATA_MID                 0x1016
#define GRP2_CFS_POWER_HK_TLM_MID                      0x1017
#define GRP2_CFS_POWER_OUT_DATA_MID                    0x1018
#define GRP2_CFS_UM_ECLSS_TLM_MID					   0x1E19
#define GRP2_CFS_MAX_TLM_MID                           0x1019

#define GRP3_CFS_MIN_TLM_MID                           0x1201
#define GRP3_CFS_CI_HK_TLM_MID                         0x1201
#define GRP3_CFS_CI_OUT_DATA_MID                       0x1202
#define GRP3_CFS_SBN_TLM_MID                           0x1203
#define GRP3_CFS_SCH_HK_TLM_MID                        0x1204
#define GRP3_CFS_SCH_DIAG_TLM_MID                      0x1205
#define GRP3_CFS_SCH_TT_HK_TLM_MID                     0x1206
#define GRP3_CFS_TO_HK_TLM_MID                         0x1207
#define GRP3_CFS_TO_OUT_DATA_MID                       0x1208
#define GRP3_CFS_TO_DATA_TYPE_MID                      0x1209
#define GRP3_CFS_TTE_MGR_HK_TLM_MID                    0x120A
#define GRP3_CFS_AUDIO_HK_TLM_MID                      0x120B
#define GRP3_CFS_AUDIO_OUT_DATA_MID                    0x120C
#define GRP3_CFS_MSM_HK_TLM_MID                        0x120D
#define GRP3_CFS_MSM_OUT_DATA_MID                      0x120E
#define GRP3_CFS_VIDEO_HK_TLM_MID                      0x120F
#define GRP3_CFS_VIDEO_OUT_DATA_MID                    0x1210
#define GRP3_CFS_CT_HK_TLM_MID                         0x1211
#define GRP3_CFS_CT_OUT_DATA_MID                       0x1212
#define GRP3_CFS_ECLS_HK_TLM_MID                       0x1213
#define GRP3_CFS_ECLS_OUT_DATA_MID                     0x1214
#define GRP3_CFS_LIGHTING_HK_TLM_MID                   0x1215
#define GRP3_CFS_LIGHTING_OUT_DATA_MID                 0x1216
#define GRP3_CFS_POWER_HK_TLM_MID                      0x1217
#define GRP3_CFS_POWER_OUT_DATA_MID                    0x1218
#define GRP3_CFS_UM_ECLSS_TLM_MID					   0x1219
#define GRP3_CFS_MAX_TLM_MID                           0x1219

#define GRP4_CFS_MIN_TLM_MID                           0x1401
#define GRP4_CFS_CI_HK_TLM_MID                         0x1401
#define GRP4_CFS_CI_OUT_DATA_MID                       0x1402
#define GRP4_CFS_SBN_TLM_MID                           0x1403
#define GRP4_CFS_SCH_HK_TLM_MID                        0x1404
#define GRP4_CFS_SCH_DIAG_TLM_MID                      0x1405
#define GRP4_CFS_SCH_TT_HK_TLM_MID                     0x1406
#define GRP4_CFS_TO_HK_TLM_MID                         0x1407
#define GRP4_CFS_TO_OUT_DATA_MID                       0x1408
#define GRP4_CFS_TO_DATA_TYPE_MID                      0x1409
#define GRP4_CFS_TTE_MGR_HK_TLM_MID                    0x140A
#define GRP4_CFS_AUDIO_HK_TLM_MID                      0x140B
#define GRP4_CFS_AUDIO_OUT_DATA_MID                    0x140C
#define GRP4_CFS_MSM_HK_TLM_MID                        0x140D
#define GRP4_CFS_MSM_OUT_DATA_MID                      0x140E
#define GRP4_CFS_VIDEO_HK_TLM_MID                      0x140F
#define GRP4_CFS_VIDEO_OUT_DATA_MID                    0x1410
#define GRP4_CFS_CT_HK_TLM_MID                         0x1411
#define GRP4_CFS_CT_OUT_DATA_MID                       0x1412
#define GRP4_CFS_ECLS_HK_TLM_MID                       0x1413
#define GRP4_CFS_ECLS_OUT_DATA_MID                     0x1414
#define GRP4_CFS_LIGHTING_HK_TLM_MID                   0x1415
#define GRP4_CFS_LIGHTING_OUT_DATA_MID                 0x1416
#define GRP4_CFS_POWER_HK_TLM_MID                      0x1417
#define GRP4_CFS_POWER_OUT_DATA_MID                    0x1418
#define GRP4_CFS_UM_ECLSS_TLM_MID					   0x1419
#define GRP4_CFS_MAX_TLM_MID                           0x1419

#endif /* _auto_cfs_mids_h_ */

