/* This will be an auto-generated header file from CCDD tools */

#ifndef _cfe_msgids_h_
#define _cfe_msgids_h_

#include "auto_cfe_mids.h"

/* Command message IDs */
#define CFE_ES_CMD_MID          GRP1_CFE_ES_CMD_MID
#define CFE_ES_SEND_HK_MID      GRP1_CFE_ES_SEND_HK_MID
#define CFE_EVS_CMD_MID         GRP1_CFE_EVS_CMD_MID
#define CFE_EVS_SEND_HK_MID     GRP1_CFE_EVS_SEND_HK_MID
#define CFE_SB_CMD_MID          GRP1_CFE_SB_CMD_MID
#define CFE_SB_SEND_HK_MID      GRP1_CFE_SB_SEND_HK_MID
#define CFE_TBL_CMD_MID         GRP1_CFE_TBL_CMD_MID
#define CFE_TBL_SEND_HK_MID     GRP1_CFE_TBL_SEND_HK_MID
#define CFE_TIME_CMD_MID        GRP1_CFE_TIME_CMD_MID
#define CFE_TIME_SEND_HK_MID    GRP1_CFE_TIME_SEND_HK_MID
#define CFE_TIME_TONE_CMD_MID   GRP1_CFE_TIME_TONE_CMD_MID
#define CFE_TIME_1HZ_CMD_MID    GRP1_CFE_TIME_HZ_CMD_MID
#define CFE_TIME_DATA_CMD_MID   GRP1_CFE_TIME_DATA_CMD_MID
#define CFE_TIME_SEND_CMD_MID   GRP1_CFE_TIME_SEND_CMD_MID

/* Telemetry message IDs */
#define CFE_ES_HK_TLM_MID             GRP1_CFE_ES_HK_TLM_MID
#define CFE_ES_SHELL_TLM_MID          GRP1_CFE_ES_SHELL_TLM_MID
#define CFE_ES_MEMSTATS_TLM_MID       GRP1_CFE_ES_MEMSTATS_TLM_MID
#define CFE_ES_APP_TLM_MID            GRP1_CFE_ES_APP_TLM_MID
#define CFE_EVS_HK_TLM_MID            GRP1_CFE_EVS_HK_TLM_MID
#define CFE_EVS_LONG_EVENT_MSG_MID    GRP1_CFE_EVS_LONG_EVENT_MSG_MID
#define CFE_EVS_SHORT_EVENT_MSG_MID   GRP1_CFE_EVS_SHORT_EVENT_MSG_MID
#define CFE_EVS_EVENT_MSG_MID         GRP1_CFE_EVS_EVENT_MSG_MID
#define CFE_SB_HK_TLM_MID             GRP1_CFE_SB_HK_TLM_MID
#define CFE_SB_STATS_TLM_MID          GRP1_CFE_SB_STATS_TLM_MID
#define CFE_SB_ALLSUBS_TLM_MID        GRP1_CFE_SB_ALLSUBS_TLM_MID
#define CFE_SB_ONESUB_TLM_MID         GRP1_CFE_SB_ONESUB_TLM_MID
#define CFE_TBL_HK_TLM_MID            GRP1_CFE_TBL_HK_TLM_MID
#define CFE_TBL_REG_TLM_MID           GRP1_CFE_TBL_REG_TLM_MID
#define CFE_TIME_HK_TLM_MID           GRP1_CFE_TIME_HK_TLM_MID
#define CFE_TIME_DIAG_TLM_MID         GRP1_CFE_TIME_DIAG_TLM_MID

#endif  /* _cfe_msgids_h_ */

